# Generated by Django 5.2.12 on 2026-08-12 20:36

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название сети')),
            ],
            options={
                'verbose_name': 'Сеть',
                'verbose_name_plural': 'Сети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Типы блюд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Ключ поиска')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена, ₽')),
                ('price_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Цена подтверждена')),
                ('rating', models.FloatField(db_index=True, default=0.0, verbose_name='Рейтинг (для сортировки)')),
                ('rating_raw', models.FloatField(default=0.0, verbose_name='Средняя оценка (для показа)')),
                ('ratings_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Количество видимых постов')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('hidden', 'Скрыта')], db_index=True, default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='posts.dishtype', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Что не так')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('resolved', 'Исправлено'), ('declined', 'Отклонена')], db_index=True, default='new', max_length=16, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата разбора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.menuitem', verbose_name='Позиция')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_menu_item_reports', to=settings.AUTH_USER_MODEL, verbose_name='Разобрал')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы')),
            ],
            options={
                'verbose_name': 'Жалоба на позицию',
                'verbose_name_plural': 'Жалобы на позиции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceNotFoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, verbose_name='Что искали')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_not_found_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заведение не найдено',
                'verbose_name_plural': 'Заведения не найдены',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалён')),
                ('draft_restaurant_source', models.CharField(blank=True, choices=[('user', 'Добавлено пользователем'), ('yandex', 'Яндекс.Карты')], default='yandex', max_length=16, verbose_name='Источник заведения')),
                ('draft_restaurant_external_id', models.CharField(blank=True, max_length=64, verbose_name='Идентификатор заведения в источнике')),
                ('draft_restaurant_name', models.CharField(blank=True, max_length=255, verbose_name='Название заведения')),
                ('draft_restaurant_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес заведения')),
                ('draft_restaurant_city', models.CharField(blank=True, max_length=100, verbose_name='Город заведения')),
                ('draft_restaurant_latitude', models.FloatField(blank=True, null=True, verbose_name='Широта заведения')),
                ('draft_restaurant_longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота заведения')),
                ('draft_menu_item_name', models.CharField(blank=True, max_length=255, verbose_name='Название позиции')),
                ('description', models.TextField(blank=True, verbose_name='Текст поста')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер / объём')),
                ('author_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка автора')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предложенная цена')),
                ('proposed_price_status', models.CharField(choices=[('none', 'Цена не предлагалась'), ('pending', 'Предложена новая цена'), ('accepted', 'Новая цена принята'), ('rejected', 'Новая цена отклонена')], default='none', max_length=16, verbose_name='Статус предложения цены')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=16, verbose_name='Статус модерации')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('possible_duplicate', models.BooleanField(db_index=True, default=False, verbose_name='Похоже на дубль')),
                ('looks_suspicious', models.BooleanField(db_index=True, default=False, verbose_name='Подозрительный ввод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_dish_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_posts', to='posts.dishtype', verbose_name='Тип блюда')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.menuitem', verbose_name='Позиция')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалён')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
            options={
                'verbose_name': 'Фото поста',
                'verbose_name_plural': 'Фото постов',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='PostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохранение',
                'verbose_name_plural': 'Сохранения',
            },
        ),
        migrations.CreateModel(
            name='PostStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('saves_count', models.PositiveIntegerField(default=0, verbose_name='Сохранения')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='posts.post')),
            ],
            options={
                'verbose_name': 'Статистика поста',
                'verbose_name_plural': 'Статистика постов',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'Добавлено пользователем'), ('yandex', 'Яндекс.Карты')], default='user', max_length=16, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='Идентификатор в источнике')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('normalized_address', models.CharField(db_index=True, editable=False, max_length=500)),
                ('normalized_city', models.CharField(db_index=True, editable=False, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('contributors_count', models.PositiveIntegerField(default=0, verbose_name='Разных авторов')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Видимых постов')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='posts.brand', verbose_name='Сеть')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='draft_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_posts', to='posts.restaurant', verbose_name='Выбранное заведение'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='posts.restaurant', verbose_name='Заведение'),
        ),
        migrations.CreateModel(
            name='RestaurantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Написание названия')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Написание адреса')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('normalized_address', models.CharField(db_index=True, editable=False, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='posts.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Синоним заведения',
                'verbose_name_plural': 'Синонимы заведений',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tag')),
            ],
            options={
                'verbose_name': 'Тег поста',
                'verbose_name_plural': 'Теги постов',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='posts.PostTag', to='posts.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='MenuItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions_count', models.PositiveIntegerField(default=0, verbose_name='Сколько людей упомянули')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.menuitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tag')),
            ],
            options={
                'verbose_name': 'Тег позиции',
                'verbose_name_plural': 'Теги позиций',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(related_name='menu_items', through='posts.MenuItemTag', to='posts.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cuisine', 'Кухня'), ('format', 'Формат еды'), ('form', 'Форма еды'), ('diet', 'Дополнительно')], db_index=True, max_length=16, verbose_name='Ось')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='taxon_unique_kind_slug'), models.UniqueConstraint(fields=('kind', 'name'), name='taxon_unique_kind_name')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='draft_taxons',
            field=models.ManyToManyField(blank=True, related_name='draft_posts', to='posts.taxon', verbose_name='Категории позиции'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='taxons',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='posts.taxon', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='default_taxons',
            field=models.ManyToManyField(blank=True, related_name='dish_types', to='posts.taxon', verbose_name='Категории по умолчанию'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк комментария',
                'verbose_name_plural': 'Лайки комментариев',
                'indexes': [models.Index(fields=['-created_at'], name='posts_comme_created_6f9992_idx')],
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='commentlike_unique_comment_user')],
            },
        ),
        migrations.CreateModel(
            name='MenuItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Написание')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Ключ поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='posts.menuitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Синоним позиции',
                'verbose_name_plural': 'Синонимы позиций',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='menuitemalias_name_trgm', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'normalized_name'), name='menuitemalias_unique_item_name')],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='posts_comme_created_d006cd_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['-created_at'], name='posts_postl_created_8fd2d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='postlike_unique_post_user'),
        ),
        migrations.AddIndex(
            model_name='postsave',
            index=models.Index(fields=['-created_at'], name='posts_posts_created_54dc93_idx'),
        ),
        migrations.AddConstraint(
            model_name='postsave',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='postsave_unique_post_user'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='restaurant_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_address'], name='restaurant_addr_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('normalized_city', 'normalized_name', 'normalized_address'), name='restaurant_unique_city_name_address'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='restaurant_unique_source_external_id'),
        ),
        migrations.AddIndex(
            model_name='restaurantalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='restaurantalias_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='restaurantalias',
            constraint=models.UniqueConstraint(fields=('restaurant', 'normalized_name', 'normalized_address'), name='restaurantalias_unique'),
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['-created_at'], name='posts_postt_created_b1a753_idx'),
        ),
        migrations.AddConstraint(
            model_name='posttag',
            constraint=models.UniqueConstraint(fields=('post', 'tag'), name='posttag_unique_post_tag'),
        ),
        migrations.AddIndex(
            model_name='menuitemtag',
            index=models.Index(fields=['-mentions_count'], name='posts_menui_mention_a89e01_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitemtag',
            constraint=models.UniqueConstraint(fields=('menu_item', 'tag'), name='menuitemtag_unique_item_tag'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='posts_post_status_9b2301_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='menuitem_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['-rating'], name='posts_menui_rating_bae229_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'normalized_name'), name='menuitem_unique_restaurant_name'),
        ),
    ]
