# Generated by Django 5.2.12 on 2026-08-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_seed_taxonomy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceNotFoundReport',
        ),
    ]
