# Generated by Django 5.2.12 on 2026-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_placenotfoundreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, verbose_name='Иконка'),
        ),
    ]
