# Generated by Django 5.2.12 on 2026-08-13 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_seed_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='post',
            name='normalized_city',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, verbose_name='Ключ города'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['normalized_city', 'status', '-created_at'], name='posts_post_normali_6d80db_idx'),
        ),
    ]
