# Generated by Django 5.2.12 on 2026-08-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_resync_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='catalog_icons/dish-types/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='catalog_icons/taxons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, verbose_name='Значок'),
        ),
    ]
