# Generated by Django 5.2.12 on 2026-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_dishtype_icon_taxon_icon_alter_dishtype_emoji_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': [models.OrderBy(models.F('sort_order'), nulls_last=True), 'name'], 'verbose_name': 'Тип блюда', 'verbose_name_plural': 'Типы блюд'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ['kind', models.OrderBy(models.F('sort_order'), nulls_last=True), 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='dishtype',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядок'),
        ),
    ]
