# Generated by Django 5.2.12 on 2026-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_trim_dish_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='kind',
            field=models.CharField(choices=[('cuisine', 'Кухня'), ('type', 'Вид')], db_index=True, max_length=16, verbose_name='Ось'),
        ),
    ]
