# Generated by Django 5.2.12 on 2026-08-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_trim_cuisines'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='Значок')),
                ('icon', models.ImageField(blank=True, upload_to='catalog_icons/dish-groups/', verbose_name='Иконка')),
                ('sort_order', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа блюд',
                'verbose_name_plural': 'Группы блюд',
                'ordering': [models.OrderBy(models.F('sort_order'), nulls_last=True), 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': [models.OrderBy(models.F('group__sort_order'), nulls_last=True), models.OrderBy(models.F('sort_order'), nulls_last=True), 'name'], 'verbose_name': 'Тип блюда', 'verbose_name_plural': 'Типы блюд'},
        ),
        migrations.AddField(
            model_name='dishtype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_types', to='posts.dishgroup', verbose_name='Группа'),
        ),
    ]
