# Generated by Django 5.2.12 on 2026-08-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_categories_to_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishtype',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': [models.OrderBy(models.F('sort_order'), nulls_last=True), 'name'], 'verbose_name': 'Тип блюда', 'verbose_name_plural': 'Типы блюд'},
        ),
        migrations.DeleteModel(
            name='DishGroup',
        ),
    ]
