# Generated by Django 5.2.12 on 2026-08-24 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_curate_dish_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Написание')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=100, verbose_name='Ключ поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='posts.dishtype', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Синоним блюда',
                'verbose_name_plural': 'Синонимы блюд',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='dishtypealias_name_trgm', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(fields=('normalized_name',), name='dishtypealias_unique_name')],
            },
        ),
    ]
