# Generated by Django 5.2.12 on 2026-08-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_dish_type_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='taxons_manual',
            field=models.BooleanField(default=False, help_text='Модератор задал категории сам, а не унаследовал от блюда. resync_taxons такие позиции не трогает: команда догоняет справочник, а догонять тут нечего — решение принято руками.', verbose_name='Категории проставлены вручную'),
        ),
    ]
