# Generated by Django 5.2.12 on 2026-08-17 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_verified(apps, schema_editor):
    """
    Все, кто зарегистрировался раньше, считаются подтверждёнными.

    Иначе новое правило заперло бы снаружи всех действующих пользователей: они
    регистрировались без письма с кодом, и подтвердить почту задним числом им
    нечем — кода на руках нет, а вход уже закрыт.
    """
    apps.get_model('users', 'User').objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_recalc_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена'),
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('signup', 'Подтверждение почты'), ('reset', 'Сброс пароля')], max_length=16, verbose_name='Назначение')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Хеш кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток ввода')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код из письма',
                'verbose_name_plural': 'Коды из писем',
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='users_email_user_id_f441c3_idx')],
            },
        ),
        migrations.RunPython(mark_existing_verified, migrations.RunPython.noop),
    ]
